In [1]:
# Create a Jupyter Notebook where, in separate cells, you define functions that return sin(x) and cos(x).
# Use Markdown cells to comment your Notebook, and describe what each function does.
# Create a third Python cell that will tabulate sin(x) and cos(x) using these previously defined functions
#     vs. x, where x is tabulated between 0 and 2 with a thousand entries. 
# Write a fourth Python cell that will use a for loop to print out the first 10 values of x, 
#     sin(x), and cos(x) in columns.

In [11]:
import numpy as np
import matplotlib.pyplot as plt

# below, I am defining a function that will return sin(x)

In [12]:
def sin_function(x):
    return np.sin(x)

# below, I am defining a function that will return cos(x)

In [13]:
def cos_function(x):
    return np.cos(x)

# below, I am tabulating sin(x) and cos(x) using the previously defined functions sin_function(x) and cos_function(x). x will be tabulated between 0 and 2 with 1000 entries

In [14]:
x = np.linspace(0, 2, 1000)
y = np.sin(x)
z = np.cos(x)
    
answer = np.zeros(shape=(1000,3))

answer[:, 0] = x # this sets x as the first column of answer
answer[:, 1] = y # this sets sin(x) as the second column of answer
answer[:, 2] = z # this sets cos(x) as the third column of answer
    
print(answer)

[[ 0.          0.          1.        ]
 [ 0.002002    0.002002    0.999998  ]
 [ 0.004004    0.00400399  0.99999198]
 ...
 [ 1.995996    0.91095639 -0.41250268]
 [ 1.997998    0.91012873 -0.41432559]
 [ 2.          0.90929743 -0.41614684]]


# below, I am printing out the first 10 values of x, sin(x), and cos(x) in columns

In [15]:
print(f"{'x':^10}{'sin(x)':^15}{'cos(x)':^15}")
for i in range(10):
    print(f"{x[i]:<10.4f}{y[i]:<15.4f}{z[i]:<15.4f}")

    x         sin(x)         cos(x)     
0.0000    0.0000         1.0000         
0.0020    0.0020         1.0000         
0.0040    0.0040         1.0000         
0.0060    0.0060         1.0000         
0.0080    0.0080         1.0000         
0.0100    0.0100         0.9999         
0.0120    0.0120         0.9999         
0.0140    0.0140         0.9999         
0.0160    0.0160         0.9999         
0.0180    0.0180         0.9998         
